// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNJugv3_95Fwq36fm9lmyRuho2sJ8OOM8',
    appId: '1:200333764758:web:0b9d3162c6e890c33cfab7',
    messagingSenderId: '200333764758',
    projectId: 'smartdoorlock-40077',
    authDomain: 'smartdoorlock-40077.firebaseapp.com',
    databaseURL: 'https://smartdoorlock-40077-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartdoorlock-40077.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNiavl3FpuCY3TnRBlQTAA1O0dvublT3o',
    appId: '1:200333764758:android:8903bc96d31408823cfab7',
    messagingSenderId: '200333764758',
    projectId: 'smartdoorlock-40077',
    databaseURL: 'https://smartdoorlock-40077-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartdoorlock-40077.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAU1hcVhnIOt-kZL_0zTeRaCmUviu2UVA',
    appId: '1:200333764758:ios:dfbe5b6e8eb40c0d3cfab7',
    messagingSenderId: '200333764758',
    projectId: 'smartdoorlock-40077',
    databaseURL: 'https://smartdoorlock-40077-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartdoorlock-40077.appspot.com',
    iosClientId: '200333764758-7micnemcqijff4fjfvvuvrgl5eijb24h.apps.googleusercontent.com',
    iosBundleId: 'com.example.trmase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAU1hcVhnIOt-kZL_0zTeRaCmUviu2UVA',
    appId: '1:200333764758:ios:dfbe5b6e8eb40c0d3cfab7',
    messagingSenderId: '200333764758',
    projectId: 'smartdoorlock-40077',
    databaseURL: 'https://smartdoorlock-40077-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartdoorlock-40077.appspot.com',
    iosClientId: '200333764758-7micnemcqijff4fjfvvuvrgl5eijb24h.apps.googleusercontent.com',
    iosBundleId: 'com.example.trmase',
  );
}
